const URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co',KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY',AUTH=`${URL}/functions/v1/nuvio-auth-v2`;
const db=supabase.createClient(URL,KEY);const $=s=>document.querySelector(s);const state={user:null,profile:null,mode:'login',chat:null,other:null,items:[],channel:null};let installEvent=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const initials=x=>esc((String(x||'N').trim()[0]||'N').toUpperCase());
function toast(t,k=''){const e=$('#toast');e.textContent=t;e.className='toast show '+k;clearTimeout(window.tt);window.tt=setTimeout(()=>e.className='toast',3000)}
function busy(b,on,text){if(!b)return;b.disabled=on;if(on){b.dataset.old=b.textContent;b.textContent=text||'Working…'}else b.textContent=b.dataset.old||b.textContent}
function authMode(m){state.mode=m;const s=m==='signup';$('#auth-title').textContent=s?'Create your account.':'Welcome back.';$('#auth-subtitle').textContent=s?'Choose a unique username and password.':'Sign in with your username.';$('#display-wrap').classList.toggle('hidden',!s);$('#auth-submit').textContent=s?'Create account':'Sign in';$('#auth-toggle').textContent=s?'Already have an account? Sign in':'Create an account';$('#password').autocomplete=s?'new-password':'current-password'}
async function auth(action,username,password,display_name=''){const r=await fetch(AUTH,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action,username,password,display_name})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'Authentication failed.');return j}
async function submitAuth(e){e.preventDefault();const b=$('#auth-submit'),u=$('#username').value.trim().toLowerCase(),p=$('#password').value,d=$('#display-name').value.trim();if(!/^[a-z0-9_]{3,24}$/.test(u))return toast('Username: 3–24 letters, numbers or _.','error');if(p.length<6)return toast('Password must be at least 6 characters.','error');busy(b,true,'Connecting…');try{if(state.mode==='signup')await auth('signup',u,p,d);const j=await auth('login',u,p);if(!j.session)throw Error('No login session returned.');const {error}=await db.auth.setSession(j.session);if(error)throw error;toast(state.mode==='signup'?'Account created.':'Welcome back.','success')}catch(e){toast(/duplicate|taken|already.*registered/i.test(e.message)?'That username is already taken.':e.message,'error')}finally{busy(b,false)}}
function showAuth(){state.user=null;$('#auth').classList.remove('hidden');$('#app').classList.add('hidden');if(state.channel){db.removeChannel(state.channel);state.channel=null}}
async function enter(user){state.user=user;const {data,error}=await db.from('nuvio_profiles').select('*').eq('id',user.id).single();if(error)return toast(error.message,'error');state.profile=data;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#profile').textContent=`@${data.username}`;$('#mobile-profile').textContent=initials(data.display_name||data.username);await loadChats();subscribeGlobal()}
async function loadChats(){const {data:ms,error}=await db.from('nuvio_conversation_members').select('conversation_id').eq('user_id',state.user.id);if(error)return toast(error.message,'error');state.items=[];for(const m of ms||[]){const {data:members}=await db.from('nuvio_conversation_members').select('user_id,nuvio_profiles(username,display_name)').eq('conversation_id',m.conversation_id);const other=(members||[]).find(x=>x.user_id!==state.user.id);if(other){const {data:c}=await db.from('nuvio_conversations').select('id,updated_at').eq('id',m.conversation_id).maybeSingle();state.items.push({id:m.conversation_id,other:other.nuvio_profiles,updated:c?.updated_at||''})}}state.items.sort((a,b)=>new Date(b.updated)-new Date(a.updated));renderChats()}
function renderChats(){const el=$('#conversation-list');if(!state.items.length){el.innerHTML='<div class="empty-side">No conversations yet.<br>Find someone to start one.</div>';return}el.innerHTML=state.items.map(c=>`<button class="conversation-item ${state.chat===c.id?'active':''}" data-id="${c.id}"><span class="avatar small">${initials(c.other.display_name||c.other.username)}</span><span><b>${esc(c.other.display_name||c.other.username)}</b><small>@${esc(c.other.username)}</small></span></button>`).join('');el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openChat(b.dataset.id))}
async function openChat(id){const c=state.items.find(x=>x.id===id);if(!c)return;state.chat=id;state.other=c.other;$('#welcome').classList.add('hidden');$('#chat').classList.remove('hidden');$('#chat-avatar').textContent=initials(c.other.display_name||c.other.username);$('#chat-name').textContent=c.other.display_name||c.other.username;$('#chat-user').textContent='@'+c.other.username;renderChats();await messages()}
async function messages(){const {data,error}=await db.from('nuvio_messages').select('id,sender_id,body,message_type,created_at,nuvio_attachments(file_name,mime_type,size_bytes,storage_path)').eq('conversation_id',state.chat).order('created_at');if(error)return toast(error.message,'error');const el=$('#messages');if(!data?.length){el.innerHTML='<div class="empty-chat"><div class="star">✦</div><b>Start the conversation</b><span>Private messages and shared files live here.</span></div>';return}el.innerHTML=data.map(m=>{const mine=m.sender_id===state.user.id,a=m.nuvio_attachments?.[0];const file=a?`<button class="file-card" data-path="${esc(a.storage_path)}"><span class="file-icon">${a.mime_type?.startsWith('image/')?'▧':'⌁'}</span><span><b>${esc(a.file_name)}</b><small>${bytes(a.size_bytes)}</small></span></button>`:'';return`<div class="message ${mine?'mine':''}"><div class="bubble">${m.body?`<div class="bubble-text">${esc(m.body).replace(/\n/g,'<br>')}</div>`:''}${file}<time>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div></div>`}).join('');el.scrollTop=el.scrollHeight;el.querySelectorAll('.file-card').forEach(b=>b.onclick=()=>download(b.dataset.path))}
const bytes=n=>{if(!n)return'';let x=n,i=0,u=['B','KB','MB','GB'];while(x>1024&&i<3){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`};
async function send(e){e.preventDefault();const input=$('#message'),body=input.value.trim();if(!body||!state.chat)return;input.value='';const {error}=await db.from('nuvio_messages').insert({conversation_id:state.chat,sender_id:state.user.id,body,message_type:'text'});if(error){input.value=body;toast(error.message,'error')}}
async function upload(){const f=$('#file').files[0];$('#file').value='';if(!f||!state.chat)return;if(f.size>50*1024*1024)return toast('Maximum file size is 50 MB.','error');const path=`${state.chat}/${state.user.id}/${crypto.randomUUID()}-${f.name.replace(/[^\w.\- ]/g,'_')}`;toast('Uploading…');const {error:up}=await db.storage.from('nuvio-files').upload(path,f,{contentType:f.type||'application/octet-stream'});if(up)return toast(up.message,'error');const {data:m,error:me}=await db.from('nuvio_messages').insert({conversation_id:state.chat,sender_id:state.user.id,body:f.name,message_type:'file'}).select('id').single();if(me)return toast(me.message,'error');const {error:ae}=await db.from('nuvio_attachments').insert({message_id:m.id,conversation_id:state.chat,uploader_id:state.user.id,storage_path:path,file_name:f.name,mime_type:f.type||'application/octet-stream',size_bytes:f.size});if(ae)toast(ae.message,'error')}
async function download(path){const {data,error}=await db.storage.from('nuvio-files').createSignedUrl(path,300);if(error)return toast(error.message,'error');location.href=data.signedUrl}
function searchModal(){modal(`<div class="modal-card"><div class="modal-head"><div><div class="label">PEOPLE</div><h2>Find someone</h2></div><button id="close" class="icon-btn">×</button></div><input id="q" class="search-input" placeholder="Search username…" autofocus><div id="results"><div class="muted">Type at least 2 characters.</div></div></div>`);$('#close').onclick=close;let timer;$('#q').oninput=()=>{clearTimeout(timer);timer=setTimeout(search,180)}}
async function search(){const q=$('#q').value.trim();if(q.length<2)return $('#results').innerHTML='<div class="muted">Type at least 2 characters.</div>';const {data,error}=await db.from('nuvio_profiles').select('id,username,display_name').ilike('username',`%${q}%`).neq('id',state.user.id).limit(20);if(error)return $('#results').innerHTML=`<div class="muted">${esc(error.message)}</div>`;if(!data?.length)return $('#results').innerHTML='<div class="muted">No users found.</div>';$('#results').innerHTML=data.map(p=>`<div class="person"><span class="avatar">${initials(p.display_name||p.username)}</span><div class="person-info"><b>${esc(p.display_name||p.username)}</b><small>@${esc(p.username)}</small></div><button class="btn secondary req" data-id="${p.id}">Chat</button></div>`).join('');document.querySelectorAll('.req').forEach(b=>b.onclick=()=>request(b.dataset.id,b))}
async function request(id,b){busy(b,true,'Sending…');const {error}=await db.from('nuvio_chat_requests').insert({sender_id:state.user.id,recipient_id:id});if(error){toast(/duplicate/i.test(error.message)?'Request already exists.':error.message,'error');return busy(b,false)}b.textContent='Requested';toast('Chat request sent.','success')}
async function profile(){const {data,error}=await db.from('nuvio_chat_requests').select('id,sender_id,created_at,nuvio_profiles!nuvio_chat_requests_sender_id_fkey(username,display_name)').eq('recipient_id',state.user.id).eq('status','pending').order('created_at',{ascending:false});modal(`<div class="modal-card"><div class="modal-head"><div><div class="label">ACCOUNT</div><h2>Profile</h2></div><button id="close" class="icon-btn">×</button></div><div class="profile-card"><span class="avatar">${initials(state.profile.display_name||state.profile.username)}</span><div><h3>${esc(state.profile.display_name||state.profile.username)}</h3><small>@${esc(state.profile.username)}</small></div></div><div class="label">CHAT REQUESTS</div><div id="requests"></div></div>`);$('#close').onclick=close;const el=$('#requests');if(error)return el.innerHTML=`<div class="muted">${esc(error.message)}</div>`;if(!data?.length)return el.innerHTML='<div class="muted">No pending requests.</div>';el.innerHTML=data.map(r=>`<div class="person"><span class="avatar">${initials(r.nuvio_profiles.display_name||r.nuvio_profiles.username)}</span><div class="person-info"><b>${esc(r.nuvio_profiles.display_name||r.nuvio_profiles.username)}</b><small>@${esc(r.nuvio_profiles.username)}</small></div><div class="request-actions"><button class="btn primary accept" data-id="${r.id}">Accept</button><button class="btn secondary reject" data-id="${r.id}">Decline</button></div></div>`).join('');document.querySelectorAll('.accept').forEach(b=>b.onclick=()=>respond(b.dataset.id,true));document.querySelectorAll('.reject').forEach(b=>b.onclick=()=>respond(b.dataset.id,false))}
async function respond(id,yes){const {error}=await db.rpc(yes?'nuvio_accept_request':'nuvio_reject_request',{p_request_id:id});if(error)return toast(error.message,'error');toast(yes?'Conversation created.':'Request declined.',yes?'success':'');close();await loadChats()}
function modal(html){$('#modal').innerHTML=html;$('#modal').classList.remove('hidden')}function close(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}
function pwa(){addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('#install').classList.remove('hidden');$('#install-start').classList.remove('hidden')});const go=async()=>{if(!installEvent)return toast('Use your browser menu and choose Install app.');installEvent.prompt();await installEvent.userChoice;installEvent=null;$('#install').classList.add('hidden');$('#install-start').classList.add('hidden')};$('#install').onclick=go;$('#install-start').onclick=go;addEventListener('appinstalled',()=>{installEvent=null;$('#install').classList.add('hidden');$('#install-start').classList.add('hidden');toast('Nuvio installed.','success')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function bind(){authMode('login');$('#auth-toggle').onclick=()=>authMode(state.mode==='login'?'signup':'login');$('#auth-form').onsubmit=submitAuth;$('#signout').onclick=()=>db.auth.signOut();$('#find').onclick=searchModal;$('#find-start').onclick=searchModal;$('#new-chat').onclick=searchModal;$('#profile').onclick=profile;$('#mobile-profile').onclick=profile;$('#composer').onsubmit=send;$('#attach').onclick=()=>$('#file').click();$('#file').onchange=upload;$('#back').onclick=()=>{$('#chat').classList.add('hidden');$('#welcome').classList.remove('hidden');state.chat=null;renderChats()};$('#chat-menu').onclick=profile;pwa()}
function subscribeGlobal(){if(state.channel)db.removeChannel(state.channel);state.channel=db.channel('nuvio-live').on('postgres_changes',{event:'*',schema:'public',table:'nuvio_messages'},p=>{if(p.new?.conversation_id===state.chat)messages();else loadChats()}).on('postgres_changes',{event:'*',schema:'public',table:'nuvio_chat_requests'},()=>{}).subscribe()}
(async()=>{bind();const {data:{session}}=await db.auth.getSession();if(session?.user)await enter(session.user);else showAuth();db.auth.onAuthStateChange(async(_,s)=>{if(s?.user&&!state.user)await enter(s.user);if(!s)showAuth()})})();
