const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const {createClient}=window.supabase;const db=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);const state={user:null,profile:null,conversation:null,other:null,realtime:[],authMode:'login',conversations:[]};let deferredInstallPrompt=null;
function toast(message,kind='info'){const el=$('#toast');el.textContent=message;el.className=`toast show ${kind}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.className='toast',3200)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function initials(n='N'){return esc(n.trim().slice(0,1).toUpperCase()||'N')}function setBusy(b,busy,label){if(!b)return;b.disabled=busy;b.dataset.original??=b.textContent;b.textContent=busy?(label||'Please wait…'):b.dataset.original}function redirectUrl(){return location.origin+location.pathname}
function setAuthMode(mode){state.authMode=mode;const signup=mode==='signup';$('#auth-title').textContent=signup?'Create your account.':'Welcome back.';$('#auth-subtitle').textContent=signup?'Pick a unique username and make your private space.':'Sign in to your conversations and files.';$('#username-field').hidden=!signup;$('#display-field').hidden=!signup;$('#username').required=signup;$('#auth-submit').textContent=signup?'Create account':'Sign in';$('#auth-toggle').textContent=signup?'Already have an account? Sign in':'Create an account';$('#resend-confirm').hidden=signup}
async function init(){setAuthMode('login');bindAuth();bindApp();setupPWA();registerSW();const {data:{session}}=await db.auth.getSession();if(session)await enterApp(session.user);else showAuth();db.auth.onAuthStateChange(async(_,session)=>{if(session?.user&&!state.user)await enterApp(session.user);if(!session)showAuth()})}
function showAuth(){$('#auth').classList.remove('hidden');$('#app').classList.add('hidden');state.user=null;state.profile=null;state.conversation=null}
async function enterApp(user){state.user=user;const {data:profile,error}=await db.from('nuvio_profiles').select('*').eq('id',user.id).single();if(error){toast(error.message,'error');return}state.profile=profile;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');renderProfile();await loadConversations();subscribeRealtime()}
function renderProfile(){const text=`${state.profile.display_name||state.profile.username} · @${state.profile.username}`;$('#profile-btn').textContent=text;$('#mobile-profile').title=text}
function bindAuth(){$('#auth-toggle').onclick=()=>setAuthMode(state.authMode==='login'?'signup':'login');$('#resend-confirm').onclick=resendConfirmation;$('#auth-form').onsubmit=async e=>{e.preventDefault();const btn=$('#auth-submit');setBusy(btn,true,'Connecting…');try{const email=$('#email').value.trim(),password=$('#password').value,username=$('#username').value.trim(),display=$('#display-name').value.trim();if(state.authMode==='signup'){if(!/^[A-Za-z0-9_]{3,24}$/.test(username))throw Error('Username must be 3–24 characters using letters, numbers or _.');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:redirectUrl(),data:{username,display_name:display||username}}});if(error)throw error;if(!data.session){toast('Account created. Check your Gmail inbox and spam for the confirmation link.','success');$('#resend-confirm').hidden=false}else toast('Welcome to Nuvio.','success')}else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error}}catch(e){toast(normalizeError(e),'error')}finally{setBusy(btn,false)}}}
async function resendConfirmation(){const email=$('#email').value.trim();if(!email){toast('Enter your email first.','error');$('#email').focus();return}const b=$('#resend-confirm');setBusy(b,true,'Sending…');try{const {error}=await db.auth.resend({type:'signup',email,options:{emailRedirectTo:redirectUrl()}});if(error)throw error;toast('Confirmation email requested. Check Gmail and spam.','success')}catch(e){toast(normalizeError(e),'error')}finally{setBusy(b,false)}}
function normalizeError(e){const m=e?.message||String(e);if(m.includes('USERNAME_TAKEN')||m.toLowerCase().includes('duplicate key'))return'That username is already taken.';if(m.toLowerCase().includes('rate limit'))return'Too many email requests. Wait a little and try again.';return m}
function setupPWA(){const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;const install=()=>{if(!deferredInstallPrompt){toast('Open your browser menu and choose Install app / Add to Home screen.');return}deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.then(r=>{if(r.outcome==='accepted')toast('Nuvio installed.','success');deferredInstallPrompt=null;hideInstall()})};addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;showInstall()});addEventListener('appinstalled',()=>{deferredInstallPrompt=null;hideInstall();toast('Nuvio is installed.','success')});$('#install-app').onclick=install;$('#welcome-install').onclick=install;if(standalone)hideInstall()}
function showInstall(){$('#install-app').hidden=false;$('#welcome-install').hidden=false}function hideInstall(){$('#install-app').hidden=true;$('#welcome-install').hidden=true}function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function bindApp(){$('#signout').onclick=()=>db.auth.signOut();$('#new-chat').onclick=openSearch;$('#search-btn').onclick=openSearch;$('#welcome-search').onclick=openSearch;$('#back-mobile').onclick=()=>{$('#chat').classList.add('hidden');$('#welcome').classList.remove('hidden');state.conversation=null};$('#profile-btn').onclick=showProfile;$('#mobile-profile').onclick=showProfile;$('#composer').onsubmit=sendText;$('#attach').onclick=()=>$('#file-input').click();$('#file-input').onchange=uploadFile}
async function loadConversations(){const {data:members,error}=await db.from('nuvio_conversation_members').select('conversation_id,user_id').eq('user_id',state.user.id);if(error){toast(error.message,'error');return}state.conversations=[];for(const m of members||[]){const {data:all}=await db.from('nuvio_conversation_members').select('user_id,nuvio_profiles(username,display_name,avatar_url)').eq('conversation_id',m.conversation_id);const other=(all||[]).find(x=>x.user_id!==state.user.id);const {data:conv}=await db.from('nuvio_conversations').select('id,updated_at').eq('id',m.conversation_id).single();if(other)state.conversations.push({id:m.conversation_id,updated_at:conv?.updated_at||'',other:other.nuvio_profiles})}state.conversations.sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));renderConversations()}
function renderConversations(){const el=$('#conversation-list');if(!state.conversations.length){el.innerHTML='<div class="empty-side">No conversations yet.<br><small>Find someone to get started.</small></div>';return}el.innerHTML=state.conversations.map(c=>`<button class="conversation-item ${state.conversation?.id===c.id?'active':''}" data-cid="${c.id}"><span class="avatar small">${initials(c.other.display_name||c.other.username)}</span><span><b>${esc(c.other.display_name||c.other.username)}</b><small>@${esc(c.other.username)}</small></span></button>`).join('');el.querySelectorAll('[data-cid]').forEach(b=>b.onclick=()=>openConversation(b.dataset.cid))}
async function openConversation(id){const c=state.conversations.find(x=>x.id===id);if(!c)return;state.conversation=c;state.other=c.other;renderConversations();$('#welcome').classList.add('hidden');$('#chat').classList.remove('hidden');$('#chat-name').textContent=c.other.display_name||c.other.username;$('#chat-username').textContent='@'+c.other.username;$('#chat-avatar').textContent=initials(c.other.display_name||c.other.username);await loadMessages()}
async function loadMessages(){if(!state.conversation)return;const {data,error}=await db.from('nuvio_messages').select('id,conversation_id,sender_id,body,message_type,created_at,nuvio_attachments(id,file_name,mime_type,size_bytes,storage_path)').eq('conversation_id',state.conversation.id).order('created_at',{ascending:true});if(error){toast(error.message,'error');return}renderMessages(data||[])}
function renderMessages(ms){const el=$('#messages');if(!ms.length){el.innerHTML='<div class="empty-chat"><div>✦</div><b>Start the conversation</b><span>Messages and shared files stay inside this private chat.</span></div>';return}el.innerHTML=ms.map(m=>{const mine=m.sender_id===state.user.id,a=m.nuvio_attachments?.[0],file=a?`<button class="file-card" data-path="${esc(a.storage_path)}"><span class="file-icon">${a.mime_type?.startsWith('image/')?'▧':'⌁'}</span><span><b>${esc(a.file_name)}</b><small>${formatBytes(a.size_bytes)}</small></span></button>`:'',body=m.body?`<div class="bubble-text">${esc(m.body).replace(/\n/g,'<br>')}</div>`:'';return`<article class="message ${mine?'mine':''}"><div class="bubble">${body}${file}<time>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div></article>`}).join('');el.scrollTop=el.scrollHeight;el.querySelectorAll('.file-card').forEach(b=>b.onclick=()=>downloadFile(b.dataset.path))}
function formatBytes(n){if(!n)return'';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return`${x<10&&i?x.toFixed(1):Math.round(x)} ${u[i]}`}
async function sendText(e){e.preventDefault();const i=$('#message-input'),body=i.value.trim();if(!body||!state.conversation)return;i.value='';const {error}=await db.from('nuvio_messages').insert({conversation_id:state.conversation.id,sender_id:state.user.id,body,message_type:'text'});if(error){toast(error.message,'error');i.value=body}}
async function uploadFile(){const f=$('#file-input').files[0];$('#file-input').value='';if(!f||!state.conversation)return;if(f.size>50*1024*1024){toast('Files are limited to 50 MB.','error');return}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${state.conversation.id}/${state.user.id}/${crypto.randomUUID()}-${safe}`;toast('Uploading…');const {error:up}=await db.storage.from('nuvio-files').upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(up){toast(up.message,'error');return}const {data:msg,error:me}=await db.from('nuvio_messages').insert({conversation_id:state.conversation.id,sender_id:state.user.id,body:f.name,message_type:f.type?.startsWith('image/')?'image':'file'}).select('id').single();if(me){toast(me.message,'error');return}const {error:ae}=await db.from('nuvio_attachments').insert({message_id:msg.id,conversation_id:state.conversation.id,uploader_id:state.user.id,storage_path:path,file_name:f.name,mime_type:f.type||'application/octet-stream',size_bytes:f.size});if(ae)toast(ae.message,'error')}
async function downloadFile(path){const {data,error}=await db.storage.from('nuvio-files').createSignedUrl(path,300);if(error){toast(error.message,'error');return}open(data.signedUrl,'_blank','noopener')}
function openSearch(){$('#modal').classList.remove('hidden');$('#modal').innerHTML='<div class="modal-backdrop"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">PEOPLE</span><h2>Find someone</h2></div><button class="icon-button" id="close-modal">×</button></div><div class="search-box"><span>⌕</span><input id="people-search" autofocus placeholder="Search username…"></div><div id="people-results" class="people-results"><div class="muted">Type at least 2 characters.</div></div></div></div>';$('#close-modal').onclick=closeModal;$('#people-search').oninput=debounce(searchPeople,250);$('#people-search').focus()}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}function debounce(fn,w){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),w)}}
async function searchPeople(){const q=$('#people-search').value.trim(),el=$('#people-results');if(q.length<2){el.innerHTML='<div class="muted">Type at least 2 characters.</div>';return}const {data,error}=await db.from('nuvio_profiles').select('id,username,display_name,avatar_url').ilike('username',`%${q}%`).neq('id',state.user.id).limit(20);if(error){el.innerHTML=`<div class="error-text">${esc(error.message)}</div>`;return}if(!data?.length){el.innerHTML='<div class="muted">No users found.</div>';return}el.innerHTML=data.map(p=>`<div class="person-result"><span class="avatar">${initials(p.display_name||p.username)}</span><div><b>${esc(p.display_name||p.username)}</b><small>@${esc(p.username)}</small></div><button class="secondary request-btn" data-user="${p.id}">Chat</button></div>`).join('');el.querySelectorAll('.request-btn').forEach(b=>b.onclick=()=>sendRequest(b.dataset.user,b))}
async function sendRequest(recipient,btn){setBusy(btn,true,'Sending…');const {error}=await db.from('nuvio_chat_requests').insert({sender_id:state.user.id,recipient_id:recipient});if(error){toast(error.message.includes('duplicate')?'A request already exists.':error.message,'error');setBusy(btn,false);return}btn.textContent='Requested';toast('Chat request sent.','success')}
async function showProfile(){const {data,error}=await db.from('nuvio_chat_requests').select('id,sender_id,created_at,nuvio_profiles!nuvio_chat_requests_sender_id_fkey(username,display_name)').eq('recipient_id',state.user.id).eq('status','pending').order('created_at',{ascending:false});$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">YOUR ACCOUNT</span><h2>Profile</h2></div><button class="icon-button" id="close-modal">×</button></div><div class="profile-hero"><span class="avatar huge">${initials(state.profile.display_name||state.profile.username)}</span><div><h3>${esc(state.profile.display_name||state.profile.username)}</h3><span>@${esc(state.profile.username)}</span></div></div><div class="request-section"><h3>Incoming requests</h3><div id="requests-list"></div></div></div></div>`;$('#close-modal').onclick=closeModal;const el=$('#requests-list');if(error){el.innerHTML=`<div class="error-text">${esc(error.message)}</div>`;return}if(!data?.length){el.innerHTML='<div class="muted">No pending requests.</div>';return}el.innerHTML=data.map(r=>`<div class="person-result"><span class="avatar">${initials(r.nuvio_profiles.display_name||r.nuvio_profiles.username)}</span><div><b>${esc(r.nuvio_profiles.display_name||r.nuvio_profiles.username)}</b><small>@${esc(r.nuvio_profiles.username)}</small></div><div class="request-actions"><button class="primary accept" data-id="${r.id}">Accept</button><button class="ghost reject" data-id="${r.id}">Decline</button></div></div>`).join('');el.querySelectorAll('.accept').forEach(b=>b.onclick=()=>respondRequest(b.dataset.id,true));el.querySelectorAll('.reject').forEach(b=>b.onclick=()=>respondRequest(b.dataset.id,false))}
async function respondRequest(id,accept){const {data,error}=await db.rpc(accept?'nuvio_accept_request':'nuvio_reject_request',{p_request_id:id});if(error){toast(error.message,'error');return}toast(accept?'Conversation created.':'Request declined.',accept?'success':'info');closeModal();await loadConversations();if(accept&&data)openConversation(data)}
function subscribeRealtime(){state.realtime.forEach(x=>db.removeChannel(x));state.realtime=[];const ch=db.channel('nuvio-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'nuvio_messages'},p=>{if(state.conversation?.id===p.new.conversation_id)loadMessages();else loadConversations()}).on('postgres_changes',{event:'*',schema:'public',table:'nuvio_chat_requests',filter:`recipient_id=eq.${state.user.id}`},()=>loadConversations()).subscribe();state.realtime.push(ch)}
addEventListener('load',init);
