import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
const secretKeys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}')
const admin=createClient(Deno.env.get('SUPABASE_URL')!,secretKeys.default??Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!)
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
function randomCode(){const b=crypto.getRandomValues(new Uint8Array(8));return 'CW-'+Array.from(b,x=>alphabet[x%alphabet.length]).join('').match(/.{1,4}/g)!.join('-')}
async function sha256(v:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
function ip(req:Request){return(req.headers.get('x-forwarded-for')?.split(',')[0]??req.headers.get('cf-connecting-ip')??'unknown').trim()}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed.'},405);try{const body=await req.json();
if(body.action==='create'){const label=String(body.label??'').trim().slice(0,60),latitude=Number(body.latitude),longitude=Number(body.longitude),precision=body.precision==='general'?'general':'exact';if(!label||!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude<-90||latitude>90||longitude<-180||longitude>180)return json({error:'Please provide a valid place name and location.'},400);const hash=await sha256(ip(req)+new Date().toISOString().slice(0,10)),since=new Date(Date.now()-3600000).toISOString();const {count}=await admin.from('ciwaan_creation_limits').select('id',{count:'exact',head:true}).eq('ip_hash',hash).gte('created_at',since);if((count??0)>=20)return json({error:'Too many addresses created from this connection. Please try again later.'},429);await admin.from('ciwaan_creation_limits').insert({ip_hash:hash});await admin.from('ciwaan_creation_limits').delete().lt('created_at',new Date(Date.now()-86400000).toISOString());const managementToken=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),management_token_hash=await sha256(managementToken);let address=null;for(let i=0;i<5;i++){const code=randomCode();const {data,error}=await admin.from('ciwaan_addresses').insert({code,label,latitude,longitude,precision,management_token_hash}).select('code,label,latitude,longitude,precision,created_at').single();if(!error){address=data;break}}if(!address)return json({error:'Could not generate a unique Ciwaan. Please try again.'},500);return json({address,managementToken})}
if(body.action==='lookup'){const code=String(body.code??'').trim().toUpperCase();if(!/^CW-[A-Z0-9]{4}-[A-Z0-9]{4}$/.test(code))return json({error:'Enter a valid Ciwaan code.'},400);const {data,error}=await admin.from('ciwaan_addresses').select('code,label,latitude,longitude,precision,created_at').eq('code',code).maybeSingle();if(error)return json({error:'Unable to look up that Ciwaan.'},500);if(!data)return json({error:'Ciwaan not found.'},404);return json({address:data})}
if(body.action==='delete'){const code=String(body.code??'').trim().toUpperCase(),token=String(body.managementToken??'');if(!code||!token)return json({error:'Missing management credentials.'},400);const hash=await sha256(token);const {data,error}=await admin.from('ciwaan_addresses').delete().eq('code',code).eq('management_token_hash',hash).select('code').maybeSingle();if(error)return json({error:'Unable to delete this Ciwaan.'},500);if(!data)return json({error:'Ciwaan not found or management permission was invalid.'},404);return json({ok:true})}
return json({error:'Unknown action.'},400)}catch(e){console.error(e);return json({error:'Unexpected server error.'},500)}})
