<script setup>
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { createMap, createMarker, addLiveLocation, computeWalkingRoute, drawRoute, clearRoute } from './googleMaps'

const screen = ref('home'), coords = ref({lat:null,lng:null}), precision = ref('exact'), label = ref('')
const locationStatus = ref('idle'), permissionOpen = ref(false), mapError = ref(''), saved = ref(loadSaved())
const active = ref(null), findCode = ref(''), findResult = ref(null), guideDistance = ref(null), guideDuration = ref(null), guideStatus = ref('starting')
let createMapInstance=null, createMarkerInstance=null, guideMapInstance=null, guideUserMarker=null, guideWatchId=null, lastRouteAt=0, lastRoutePoint=null
const navOpen = computed(()=>['home','find','explore','saved','address','created'].includes(screen.value))
function loadSaved(){try{return JSON.parse(localStorage.getItem('ciwaan_places')||'[]')}catch{return []}}
function persist(){localStorage.setItem('ciwaan_places',JSON.stringify(saved.value))}
function openCreate(){screen.value='create';mapError.value=''}
function goHome(){stopGuide();screen.value='home';mapError.value=''}
function askLocation(){permissionOpen.value=true}
function requestLocation(){permissionOpen.value=false;if(!navigator.geolocation){locationStatus.value='unsupported';return}locationStatus.value='requesting';navigator.geolocation.getCurrentPosition(({coords:c})=>{coords.value={lat:c.latitude,lng:c.longitude};locationStatus.value='granted';screen.value='confirm'},e=>{locationStatus.value=e.code===1?'denied':'error'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
function chooseGeneral(){precision.value='general';askLocation()}
function formatCoords(p){return p?.lat!=null?`${Number(p.lat).toFixed(6)}°, ${Number(p.lng).toFixed(6)}°`:'Location unavailable'}
function makeCode(){return `CW-${Math.random().toString(36).slice(2,6).toUpperCase()}-${Math.random().toString(36).slice(2,4).toUpperCase()}`}
function savePlace(){if(coords.value.lat==null)return;const p={code:makeCode(),label:label.value.trim()||'Unnamed place',lat:coords.value.lat,lng:coords.value.lng,precision:precision.value,createdAt:Date.now()};saved.value=[p,...saved.value].slice(0,100);persist();active.value=p;screen.value='created'}
function shareWhatsApp(p=active.value){if(!p)return;const text=`Ciwaan: ${p.label}\nCode: ${p.code}\nLocation: https://www.openstreetmap.org/?mlat=${p.lat}&mlon=${p.lng}#map=18/${p.lat}/${p.lng}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
async function copyCiwaan(){if(active.value){await navigator.clipboard?.writeText(active.value.code);locationStatus.value='copied'}}
function showSaved(p){active.value=p;screen.value='address'}
async function initCreateMap(){await nextTick();const el=document.getElementById('create-map');if(!el||coords.value.lat==null)return;createMapInstance?.remove();createMapInstance=createMap(el,[coords.value.lng,coords.value.lat],18);createMapInstance.on('load',()=>{createMarkerInstance=createMarker(createMapInstance,[coords.value.lng,coords.value.lat],{draggable:true});createMarkerInstance.on('dragend',()=>{const p=createMarkerInstance.getLngLat();coords.value={lat:p.lat,lng:p.lng}});createMapInstance.on('click',e=>{coords.value={lat:e.lngLat.lat,lng:e.lngLat.lng};createMarkerInstance.setLngLat([e.lngLat.lng,e.lngLat.lat])})})}
function distanceMeters(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,d1=(b.lat-a.lat)*Math.PI/180,d2=(b.lng-a.lng)*Math.PI/180,x=Math.sin(d1/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(d2/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
async function initGuideMap(){await nextTick();if(!active.value)return;const el=document.getElementById('guide-map');if(!el)return;guideMapInstance?.remove();guideMapInstance=createMap(el,[active.value.lng,active.value.lat],17);guideMapInstance.on('load',()=>{createMarker(guideMapInstance,[active.value.lng,active.value.lat],{color:'#0F172A'});addLiveLocation(guideMapInstance);startGuideWatch()})}
function startGuideWatch(){if(!navigator.geolocation){guideStatus.value='unsupported';return}guideStatus.value='waiting';navigator.geolocation.getCurrentPosition(updateGuidePosition,()=>{guideStatus.value='denied'},{enableHighAccuracy:true,timeout:15000,maximumAge:2000});guideWatchId=navigator.geolocation.watchPosition(updateGuidePosition,()=>{guideStatus.value='denied'},{enableHighAccuracy:true,timeout:15000,maximumAge:2000})}
async function updateGuidePosition(pos){if(!guideMapInstance||!active.value)return;const cur={lat:pos.coords.latitude,lng:pos.coords.longitude};coords.value=cur;guideStatus.value='active';if(!guideUserMarker)guideUserMarker=createMarker(guideMapInstance,[cur.lng,cur.lat],{color:'#0052FF'});else guideUserMarker.setLngLat([cur.lng,cur.lat]);guideMapInstance.easeTo({center:[cur.lng,cur.lat],duration:500});if((!lastRoutePoint||distanceMeters(lastRoutePoint,cur)>15)&&Date.now()-lastRouteAt>=5000){lastRouteAt=Date.now();lastRoutePoint=cur;try{const r=await computeWalkingRoute(cur,active.value);guideDistance.value=r.distanceKm;guideDuration.value=r.durationMin;drawRoute(guideMapInstance,r.geojson)}catch(e){mapError.value=`Could not update walking route: ${e.message}`}}}
function stopGuide(){if(guideWatchId!=null)navigator.geolocation?.clearWatch(guideWatchId);guideWatchId=null;lastRouteAt=0;lastRoutePoint=null;guideUserMarker=null;if(guideMapInstance){clearRoute(guideMapInstance);guideMapInstance.remove();guideMapInstance=null}}
function guideTo(p){active.value=p;mapError.value='';guideDistance.value=null;guideDuration.value=null;guideStatus.value='starting';screen.value='guide'}
function searchCiwaan(){const q=findCode.value.trim().toUpperCase();findResult.value=saved.value.find(p=>p.code.toUpperCase()===q)||null}
watch(screen,async v=>{if(v!=='guide')stopGuide();if(v==='confirm')await initCreateMap();if(v==='guide')await initGuideMap()})
onBeforeUnmount(()=>{stopGuide();createMapInstance?.remove()})
</script>

<template><div class="app-shell">
<header v-if="screen!=='guide'" class="topbar"><button class="brand" @click="goHome"><span class="brand-mark"><span></span></span><strong>Ciwaan</strong></button><button class="top-link" @click="screen='explore'">Explore</button></header>
<main class="content">
<section v-if="screen==='home'" class="hero"><div><div class="eyebrow"><span class="live-dot"></span>DIGITAL ADDRESSING</div><h1>Give every place<br><em>an address.</em></h1><p class="lead">Create a precise Ciwaan for a home, business, meeting point, or anywhere else — then share it instantly.</p><button class="primary-cta" @click="openCreate"><span>＋</span>Create Ciwaan</button></div><div class="hero-map"><div class="map-grid"></div><div class="map-pin">⌖</div><div class="map-label">OpenStreetMap powered</div></div></section>
<section v-else-if="screen==='create'" class="flow-card"><button class="back" @click="goHome">← Back</button><div class="section-kicker">NEW CIWAAN</div><h2>Where should we<br>place it?</h2><p>Choose how precisely you want your location represented.</p><div v-if="locationStatus==='denied'" class="notice">Location permission was denied. Enable location for Ciwaan in device settings and try again.</div><div v-if="locationStatus==='unsupported'" class="notice">This device doesn't provide location services.</div><button class="location-option exact" :disabled="locationStatus==='requesting'" @click="precision='exact';askLocation()"><span class="option-icon">⌖</span><span><b>{{locationStatus==='requesting'?'Finding your location…':'Exact location'}}</b><small>Pinpoint this place using GPS</small></span><span class="arrow">→</span></button><button class="location-option general" @click="chooseGeneral"><span class="option-icon">◌</span><span><b>General location</b><small>Use an approximate area</small></span><span class="arrow">→</span></button><p class="privacy-note">No account required. Location is requested only after you choose a location option.</p></section>
<section v-else-if="screen==='confirm'" class="flow-card wide"><button class="back" @click="screen='create'">← Back</button><div class="section-kicker">CONFIRM LOCATION</div><h2>Pin the exact spot.</h2><p>Drag the marker or tap the map to adjust it.</p><div v-if="mapError" class="notice">{{mapError}}</div><div id="create-map" class="real-map"></div><div class="coordinate-card"><span>⌖</span><div><b>{{formatCoords(coords)}}</b><small>{{precision==='exact'?'Exact location':'General location'}}</small></div></div><input v-model="label" class="name-input" maxlength="60" placeholder="Name this place (e.g. My Home)"><button class="primary-cta full" @click="savePlace">Create my Ciwaan <span>→</span></button></section>
<section v-else-if="screen==='created'" class="flow-card"><div class="section-kicker">ADDRESS READY</div><h2>Your Ciwaan<br>is ready.</h2><p>Share this location directly with someone who needs to find you.</p><div class="address-card"><small>CIWAAN</small><strong>{{active?.code}}</strong><b>{{active?.label}}</b><span>{{formatCoords(active)}}</span></div><button class="primary-cta full" @click="shareWhatsApp()">Share on WhatsApp</button><div class="action-row"><button @click="copyCiwaan">{{locationStatus==='copied'?'Copied':'Copy code'}}</button><button @click="guideTo(active)">Guide Me</button></div><button class="back" @click="goHome">Done</button></section>
<section v-else-if="screen==='find'" class="flow-card wide"><div class="section-kicker">FIND</div><h2>Find a Ciwaan.</h2><p>Enter a Ciwaan code to open a saved location.</p><div class="search-box input-search"><input v-model="findCode" @keyup.enter="searchCiwaan" placeholder="e.g. CW-A7K2-QP"><button @click="searchCiwaan">Find</button></div><div v-if="findResult" class="address-card"><small>FOUND</small><strong>{{findResult.code}}</strong><b>{{findResult.label}}</b><span>{{formatCoords(findResult)}}</span><button class="primary-cta full" @click="showSaved(findResult)">Open location</button></div><div v-else-if="findCode" class="empty">No saved Ciwaan with that code.</div></section>
<section v-else-if="screen==='explore'" class="flow-card wide"><button class="back" @click="goHome">← Back</button><div class="section-kicker">EXPLORE</div><h2>Discover places.</h2><p>Open a Ciwaan you've received or browse your saved places.</p><button class="primary-cta full" @click="screen='find'">Find a Ciwaan <span>→</span></button><button class="primary-cta full secondary-cta" @click="screen='saved'">Browse saved places <span>→</span></button></section>
<section v-else-if="screen==='saved'" class="flow-card wide"><button class="back" @click="screen='explore'">← Back</button><div class="section-kicker">SAVED</div><h2>Your places.</h2><div v-if="saved.length" class="saved-list"><button v-for="p in saved" :key="p.code" class="saved-row" @click="showSaved(p)"><span class="option-icon">⌖</span><span><b>{{p.label}}</b><small>{{p.code}} · {{p.precision}}</small></span><span>→</span></button></div><div v-else class="empty">No saved places yet.</div></section>
<section v-else-if="screen==='address'" class="flow-card"><button class="back" @click="screen='saved'">← Back</button><div class="section-kicker">CIWAAN</div><h2>{{active?.label}}</h2><div class="address-card"><small>{{active?.code}}</small><strong>{{formatCoords(active)}}</strong><span>{{active?.precision==='exact'?'Exact location':'General location'}}</span></div><button class="primary-cta full" @click="shareWhatsApp(active)">Share on WhatsApp</button><button class="primary-cta full secondary-cta" @click="guideTo(active)">Guide Me</button></section>
<section v-else-if="screen==='guide'" class="guide-screen"><div id="guide-map" class="guide-map"></div><div class="guide-overlay"><button class="guide-exit" @click="goHome">← Exit</button><div v-if="mapError" class="notice">{{mapError}}</div></div><div class="guide-panel"><div class="section-kicker">LIVE WALKING NAVIGATION</div><h2>{{active?.label}}</h2><p v-if="guideDistance!==null"><strong>{{guideDistance<1?(guideDistance*1000).toFixed(0)+' m':guideDistance.toFixed(2)+' km'}}</strong> remaining<span v-if="guideDuration!==null"> · about {{guideDuration}} min walking</span></p><p v-else>{{guideStatus==='denied'?'Location permission is required for live guidance.':'Waiting for your live location…'}}</p><button v-if="guideStatus==='denied'" class="primary-cta full" @click="askLocation()">Allow location</button></div></section>
</main>
<nav v-if="navOpen" class="bottom-dock"><button :class="{active:screen==='home'}" @click="goHome"><span>⌂</span><small>Home</small></button><button :class="{active:screen==='find'}" @click="screen='find'"><span>⌕</span><small>Find</small></button><button class="create-fab" @click="openCreate">＋</button><button :class="{active:['explore','saved','address'].includes(screen)}" @click="screen='explore'"><span>⌖</span><small>Explore</small></button></nav><footer v-if="navOpen" class="credit">Made by Raazim Tech</footer>
<div v-if="permissionOpen" class="modal-backdrop" @click.self="permissionOpen=false"><div class="permission-modal"><div class="permission-icon">⌖</div><h3>Use your location?</h3><p>Ciwaan needs your device location to place your address accurately and to show your live position when you use Guide Me.</p><p class="modal-note">Your location is requested only for this feature. You can deny access at any time.</p><div class="modal-actions"><button @click="permissionOpen=false">Not now</button><button class="primary-cta" @click="requestLocation">Continue</button></div></div></div>
</div></template>
