create table if not exists public.ciwaan_addresses (id uuid primary key default gen_random_uuid(), code text not null unique, label text not null, latitude double precision not null check (latitude between -90 and 90), longitude double precision not null check (longitude between -180 and 180), precision text not null default 'exact' check (precision in ('exact','general')), management_token_hash text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists ciwaan_addresses_code_idx on public.ciwaan_addresses(code);
alter table public.ciwaan_addresses enable row level security;
create table if not exists public.ciwaan_creation_limits (id bigint generated by default as identity primary key, ip_hash text not null, created_at timestamptz not null default now());
create index if not exists ciwaan_creation_limits_ip_created_idx on public.ciwaan_creation_limits(ip_hash, created_at);
alter table public.ciwaan_creation_limits enable row level security;
